# Development configuration for Market Data Ingestion Service

[service]
service_name = "market-data-ingestion-dev"
port = 8080
worker_threads = 2
max_concurrent_collections = 10

[alpha_vantage]
base_url = "https://www.alphavantage.co/query"
api_key = "${ALPHA_VANTAGE_API_KEY}"
timeout_seconds = 30
max_retries = 3

[rate_limits]
calls_per_minute = 5
calls_per_day = 500
premium_calls_per_minute = 75
premium_calls_per_day = 75000
is_premium = false

[collection]
default_symbols = ["AAPL", "GOOGL", "MSFT", "AMZN", "TSLA"]
priority_symbols = ["SPY", "QQQ"]
collection_intervals = ["5min", "1hour", "1day"]
max_batch_size = 100
parallel_collections = 5

[data_quality]
quality_threshold = 70
enable_deduplication = true
max_price_deviation = 0.2  # 20% max deviation for development
volume_threshold = 1000

[storage]
batch_size = 100
flush_interval_seconds = 30
enable_compression = false  # Disabled for easier debugging
retention_days = 30 