# Production configuration for Market Data Ingestion Service

[service]
service_name = "market-data-ingestion"
port = 8080
worker_threads = 8
max_concurrent_collections = 100

[alpha_vantage]
base_url = "https://www.alphavantage.co/query"
api_key = "${ALPHA_VANTAGE_API_KEY}"
timeout_seconds = 30
max_retries = 5

[rate_limits]
calls_per_minute = 75
calls_per_day = 75000
premium_calls_per_minute = 600
premium_calls_per_day = 200000
is_premium = true

[collection]
default_symbols = [
    # Major stocks
    "AAPL", "GOOGL", "MSFT", "AMZN", "TSLA", "NVDA", "META", "NFLX",
    # ETFs
    "SPY", "QQQ", "IWM", "VTI", "VEA", "VWO",
    # Financial sector
    "JPM", "BAC", "WFC", "GS", "MS",
    # Technology
    "ORCL", "ADBE", "CRM", "INTC", "AMD",
    # Healthcare
    "JNJ", "PFE", "UNH", "ABBV", "MRK",
    # Energy
    "XOM", "CVX", "COP", "EOG", "SLB"
]

priority_symbols = [
    "SPY",    # S&P 500 ETF
    "QQQ",    # NASDAQ 100 ETF
    "IWM",    # Russell 2000 ETF
    "VIX",    # Volatility Index
    "GLD",    # Gold ETF
    "TLT",    # 20+ Year Treasury Bond ETF
    "DXY"     # US Dollar Index
]

collection_intervals = ["1min", "5min", "15min", "30min", "1hour", "1day"]
max_batch_size = 5000
parallel_collections = 25

[data_quality]
quality_threshold = 85
enable_deduplication = true
max_price_deviation = 0.15  # 15% max deviation
volume_threshold = 10000

[storage]
batch_size = 2000
flush_interval_seconds = 15
enable_compression = true
retention_days = 1095  # 3 years 