[service]
service_name = "market-data-ingestion"
port = 3000
worker_threads = 4
max_concurrent_collections = 3

[alpha_vantage]
base_url = "https://www.alphavantage.co/query"
api_key = "demo"  # Replace with actual API key
timeout_seconds = 30
max_retries = 3

[rate_limits]
calls_per_minute = 5
calls_per_day = 500
premium_calls_per_minute = 75
premium_calls_per_day = 75000
is_premium = false

[collection]
default_symbols = ["AAPL", "GOOGL", "MSFT", "TSLA", "AMZN"]
priority_symbols = ["SPY", "QQQ", "IWM"]
collection_intervals = ["1min", "5min", "15min", "1hour", "1day"]
max_batch_size = 100
parallel_collections = 3

[data_quality]
quality_threshold = 70
enable_deduplication = true
max_price_deviation = 0.1
volume_threshold = 1000

[storage]
batch_size = 100
flush_interval_seconds = 60
enable_compression = true
retention_days = 365

[database]
# ClickHouse configuration
clickhouse_url = "http://localhost:8123"
clickhouse_database = "quantumtrade"
clickhouse_username = "default"
clickhouse_password = ""
clickhouse_connection_timeout = 30
clickhouse_query_timeout = 60
clickhouse_max_connections = 100
clickhouse_retry_attempts = 3

# Redis configuration
redis_url = "redis://localhost:6379"
redis_pool_size = 10
redis_connection_timeout = 30
redis_default_ttl = 3600
redis_max_connections = 100 