# services/data-ingestion/config/data-ingestion.toml
# QuantumTrade AI Data Ingestion Service Configuration

[yahoo_finance]
base_url = "https://query1.finance.yahoo.com"
timeout_seconds = 30
max_retries = 3
retry_delay_seconds = 2
user_agent = "QuantumTrade-AI/1.0"
rate_limit_per_minute = 60

[reddit]
# These should be set via environment variables for security
client_id = "${REDDIT_CLIENT_ID}"
client_secret = "${REDDIT_CLIENT_SECRET}"
username = "${REDDIT_USERNAME}"
password = "${REDDIT_PASSWORD}"
user_agent = "QuantumTrade-AI/1.0"
base_url = "https://oauth.reddit.com"
timeout_seconds = 30
max_retries = 3
rate_limit_per_minute = 60
subreddits = [
    "wallstreetbets",
    "stocks", 
    "investing",
    "SecurityAnalysis",
    "StockMarket"
]
min_score = 10
max_posts_per_request = 100

[news]
# Set via environment variable for security
api_key = "${NEWS_API_KEY}"
base_url = "https://newsapi.org/v2"
timeout_seconds = 30
max_retries = 3
rate_limit_per_minute = 100
sources = [
    "bloomberg",
    "reuters", 
    "financial-post",
    "the-wall-street-journal"
]
languages = ["en"]
max_articles_per_request = 100

[scheduler]
# Cron expressions (second minute hour day month dayofweek)
market_data_cron = "0 */5 * * * *"        # Every 5 minutes
reddit_sentiment_cron = "0 */15 * * * *"   # Every 15 minutes  
news_sentiment_cron = "0 */30 * * * *"     # Every 30 minutes
cleanup_cron = "0 0 2 * * *"               # Daily at 2 AM
enable_market_hours_only = true
timezone = "America/New_York"

[rate_limits]
requests_per_minute = 100
burst_capacity = 10
backoff_multiplier = 2.0
max_backoff_seconds = 60

[symbols]
primary_symbols = [
    "AAPL", "GOOGL", "MSFT", "AMZN", "TSLA", "META",
    "NVDA", "NFLX", "DIS", "SPY", "QQQ", "IWM"
]
watchlist_symbols = [
    "AMD", "INTC", "CRM", "ORCL", "ADBE", "PYPL"
]
crypto_symbols = [
    "BTC-USD", "ETH-USD", "ADA-USD"
]
max_symbols_per_batch = 50

[storage]
batch_size = 1000
buffer_timeout_seconds = 60
max_memory_buffer_mb = 100
enable_compression = true